### ISSUE TITLE
Tags not visible over white images

### ISSUE THREAD

**Issue by siddhant1** [ossn/fixme#103]
Tags are not visible over white images , add a black tint in background so tags can be seen.
Sending in a PR.

**Comment by siddhant1** [comment]
I think I should look into this next. Should I add it ? @bacharakis @alexdor

**Comment by alexdor** [comment]
This goes against the design, so @bacharakis has to decide on this one

**Comment by bacharakis** [comment]
@siddhant1 can you please share a screenshot of the design you have in mind in order to help us assess this? 
Thank you so much
