### ISSUE TITLE
Fix the "learn more" behavior

### ISSUE THREAD

**Issue by bacharakis** [ossn/fixme#11]
Current behavior:
![screenshot from 2018-09-26 16-32-13](https://user-images.githubusercontent.com/1435040/46110630-dc08d400-c1a9-11e8-8594-4c93d7652892.png)

Expected behavior: When you click learn more, in the main page, you page should scroll and put the "I do my magic in" in the middle of the page!

![screenshot from 2018-09-26 16-32-35](https://user-images.githubusercontent.com/1435040/46110643-e6c36900-c1a9-11e8-89ef-5ef3a644d726.png)

**Comment by yunduz** [comment]
Bug is reproducible on Firefox 62.0.
Works as expected on Chrome 69.0.3497.100.

**Comment by himankpathak** [comment]
Hi @bacharakis, created a PR to fix this issue.
