### ISSUE TITLE
The image resolution is super bad (check screenshot)

### ISSUE THREAD

**Issue by siddhant1** [ossn/fixme#123]
![image](https://user-images.githubusercontent.com/30566406/53577803-5516b800-3b9c-11e9-8762-d80499512b6a.png)

**Comment by siddhant1** [comment]
@alexdor @bacharakis

**Comment by siddhant1** [comment]
I think it should look something like this 
![image](https://user-images.githubusercontent.com/30566406/53577927-8abba100-3b9c-11e9-8a05-c1902df8a1e3.png)
I have a fix ready

**Comment by alexdor** [comment]
Yeah your change looks better than the existing one

**Comment by siddhant1** [comment]
Should I make in the change? @alexdor @bacharakis

**Comment by alexdor** [comment]
Yeah send a pr : )

**Comment by ashu8912** [comment]
just make sure this is done for mobile screens only.... for larger screens the old one looks good 
@alexdor what do you think on this one

**Comment by siddhant1** [comment]
![image](https://user-images.githubusercontent.com/30566406/53627420-6c9e8100-3c2e-11e9-8f28-7250b269e610.png)

![image](https://user-images.githubusercontent.com/30566406/53627459-89d34f80-3c2e-11e9-94f3-574e2331d503.png)

**Comment by siddhant1** [comment]
@alexdor @bacharakis

**Comment by alexdor** [comment]
yeah open a pr @siddhant1

**Comment by siddhant1** [comment]
Closing , since fixed
