### ISSUE TITLE
Form elements do not have associated labels

### ISSUE THREAD

**Issue by alexdor** [ossn/fixme#20]
Labels ensure that form controls are announced properly by assistive technologies, like screen readers. [Learn more](https://dequeuniversity.com/rules/axe/2.2/label?application=lighthouse).

Failing Elements
```
<input type="checkbox" readonly="">
```

Failing elements on the main page
```
<input autocapitalize="none" autocomplete="off" autocorrect="off" id="react-select-2-input" spellcheck="false" tabindex="0" type="text" aria-autocomplete="list" value="" style="box-sizing: content-box; width: 2px; background: 0px center; border: 0px; font-size: inherit; opacity: 1; outline: 0px; padding: 0px; color: inherit;">
```

**Comment by ailishb** [comment]
Failing form element on the main page can be addressed, but the <input type="checkbox" readonly=""> failing elements seem to be within the issue descriptions themselves.

**Comment by alexdor** [comment]
@ailishb if that's the case you can ignore it  : )

**Comment by tabshaikh** [comment]
@alexdor Should this issue be closed, so there is something more to do in this

**Comment by alexdor** [comment]
Thanks, @tabshaikh : ) closing this issue
