### ISSUE TITLE
Progressive web app improvments

### ISSUE THREAD

**Issue by alexdor** [ossn/fixme#21]
- [x] User will not be prompted to Install the Web App, because manifest.json does not have a PNG icon of at least 192px. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/install-prompt)
- [x] Website is not configured for a custom splash screen, because manifest does not have a PNG icon of at least 512px. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/custom-splash-screen)

**Comment by Muljayan** [comment]
Hi @alexdor are there any alternative files of the logo i can work with other than the .ico file in the ./public folder? If so where can i find them.

**Comment by alexdor** [comment]
Hi @Muljayan there are also this https://github.com/ossn/fixme/blob/master/src/components/FixMeNavbar/logo-fixme.svg and this https://github.com/ossn/fixme/blob/master/screens/elements/Icon_Fixme.png

**Comment by Muljayan** [comment]
Thank you , I should be able to work with these.
