### ISSUE TITLE
Ensure text remains visible during webfont load

### ISSUE THREAD

**Issue by alexdor** [ossn/fixme#22]
Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading. [Learn more](https://developers.google.com/web/updates/2016/02/font-display)

**Comment by himankpathak** [comment]
Google fonts API does not support font-display property yet. [Learn more](https://github.com/google/fonts/issues/358)
How should we go about resolving this issue? @alexdor

**Comment by alexdor** [comment]
@himankpathak I think the best solution here is to download the fonts and include them in the project. That will allow us to use the font-display and it would load the fonts faster (because we use http2 so we will skip quite a few round trips). What do you think?

**Comment by himankpathak** [comment]
@alexdor Yea, I was thinking the same to download and serve them through our project itself.
Also, there is no static directory so should I create a font directory in public or a static in src?

**Comment by himankpathak** [comment]
@alexdor Also I wanted to ask why do we use Raleway as the main font when numbers in Raleway font look up & down? Any specific reason for it?

**Comment by alexdor** [comment]
@himankpathak The designers used it so we had to : )

**Comment by himankpathak** [comment]
Okay @alexdor :P
I am really liking this project, great work done by you and @bacharakis.
Will love to help you out with other issue and features. :smile:

**Comment by alexdor** [comment]
Thanks @himankpathak : ) You could always try to tackle #15 or this comment https://github.com/ossn/fixme/issues/28#issuecomment-430454655
