### ISSUE TITLE
Background and foreground colors do not have a sufficient contrast ratio.

### ISSUE THREAD

**Issue by alexdor** [ossn/fixme#27]
Low-contrast text is difficult or impossible for many users to read. [Learn more](https://dequeuniversity.com/rules/axe/2.2/color-contrast?application=lighthouse)

Failing elements on project page:
```
<a href="https://docs.google.com/forms/d/e/1FAIpQLSfFXvaTB9BXx7AEAmght09VcFW1Zq-lqeaKHRzjPjiczzAlrQ/viewform">in this form</a>
```

```
<span class="text-muted mt-2 small fixme-footer-moz-text">Mozilla is a global non-profit dedicated to putting you in control of your online experience and shaping the future of the web for the public good. Visit us at mozilla.org</span>

```

Failing elements on main page:
```
<h6 class="home-about-you-title mb-2">TELL US A BIT ABOUT YOURSELF</h6>
```

```
<div class="css-1492t68">type in your favorite languages</div>
```

```
<span>our latest tweets</span>
```

```
<div class="home-twitter-tweet">Latest issue to fix for project Bootstrap! HELP! https://fixmeparser.com/issues#1825 </div>
```

```
<span class="text-muted mt-2 small fixme-footer-moz-text">Mozilla is a global non-profit dedicated to putting you in control of your online experience and shaping the future of the web for the public good. Visit us at mozilla.org</span>
```

Failing elements for issues page:
```

<span class="mb-4 align-self-start">Tue Sep 18 2018</span>
```

```
<span class="text-capitalize ml-1">moderate</span>
```

```
<span class="text-capitalize ml-1">javascript</span>
```

```
<span class="text-capitalize ml-1">Issue</span>
```

```
<code>a</code>
```

```
<code>p</code>
```

```
<span class="mb-4 align-self-start">Tue Sep 18 2018</span>
```

```
<span class="text-capitalize ml-1">moderate</span>
```

```
<span class="text-capitalize ml-1">typescript</span>
```

```
<span class="text-capitalize ml-1">enhancement</span>
```

```
<span class="mb-4 align-self-start">Tue Sep 18 2018</span>
```

**Comment by himankpathak** [comment]
hi @alexdor, I would like to work on this issue.

**Comment by alexdor** [comment]
Hi @himankpathak, as far as I know, nobody is working on this issues, so you can go ahead and work on it.

I can't add you as an assignee for some reason though, it  might be because you aren't part of the GitHub organization

**Comment by himankpathak** [comment]
@alexdor I am a part of the mozillacampusclub organization but not of OSSN.
Do I need to join OSSN before creating the PR?

Almost finished working on this issue, will create the PR today itself.

**Comment by himankpathak** [comment]
Hi @alexdor, need you to reviews these color changes on home page:

Current color contrast:
![current color contrast](https://user-images.githubusercontent.com/26011845/47154389-d2cddb80-d2ff-11e8-8064-485df8d206c1.png)

color contrast suggested by Axe:
![axe color contrast](https://user-images.githubusercontent.com/26011845/47154464-09a3f180-d300-11e8-8b5b-c6a7b5872c72.png)

Should I change them or the current one looks good?
Also I can't view issue page so how am i supposed to fix colors on that page?

**Comment by bacharakis** [comment]
Good work @himankpathak ! 
I like the new colors! However, it's still hard to read the words in the tags which is relevant to the width of the letters.

Is there a way to change the width a bit?
Thank you

**Comment by himankpathak** [comment]
yep! I increased the font-weight they look good now. @bacharakis 
How can I view the issues page to fix color contrast over there?

**Comment by bacharakis** [comment]
@himankpathak you would need to setup the [backend](https://github.com/ossn/fixme_backend).

**Comment by alexdor** [comment]
@himankpathak if you don't want to set up the backend, you can remove lines 45 till 50 from here https://github.com/ossn/fixme/blob/master/src/conf/endpoints.ts#L45 but don't commit it

**Comment by himankpathak** [comment]
I did setup the backend but I am recieveing error on issues page.

> Showing 0-0 of 0 issues

> Couldn't find any issues with your criteria

I tried @alexdor's advice and it worked :relieved:
