### ISSUE TITLE
Required information not starred for adding projects

### ISSUE THREAD

**Issue by jasmineflorencio** [ossn/fixme#32]
The form to add a new project on the [project](https://fixme.ossn.club/projects) page doesn't indicate whether information is required or not. Currently users can submit complete blank forms so I'm not sure if there are certain fields that can be left blank or if all fields should be filled out.

**Comment by LucyeoH** [comment]
Use this form instead - https://docs.google.com/forms/d/e/1FAIpQLSeyXGN-hywy9oX-By6qf4lmhP62bz2IDSxOs9AkhzQsjBGGdQ/formResponse

**Comment by tabshaikh** [comment]
@alexdor i made a pr but i think changes would have to be done before it merges
