### ISSUE TITLE
Setup displays on project page even if setup isn't specified

### ISSUE THREAD

**Issue by jasmineflorencio** [ossn/fixme#35]
Currently on the [projects](https://fixme.ossn.club/projects) page for a project, it just displays "setup" when a setup time has not been specified.
![screen shot 2018-09-27 at 12 18 58 pm](https://user-images.githubusercontent.com/23109409/46169293-88e95c80-c24f-11e8-8dbc-cc7064ea6b7a.png)

**Comment by tabshaikh** [comment]
I would like to work on this issue, any files to begin with as I am new to this repo :)

**Comment by tabshaikh** [comment]
@alexdor while setting up the repo I am getting this error again and again 
![error](https://user-images.githubusercontent.com/31198893/46931210-de06da00-d067-11e8-8759-679db25318d4.png)
Please can you help

**Comment by alexdor** [comment]
@tabshaikh you issues is the same as #49 , try [this](https://github.com/ossn/fixme/issues/49#issuecomment-429783095) solution and let me know if it worked : )

**Comment by tabshaikh** [comment]
@alexdor some different error popping up now
![error](https://user-images.githubusercontent.com/31198893/46951230-ff39eb80-d0a4-11e8-90be-0be30115cac2.png)

**Comment by alexdor** [comment]
@tabshaikh pull the latest changes againg and try again : )

**Comment by tabshaikh** [comment]
@alexdor i made a pr and i am not sure if the changes are right as i am new to the repo.
One more issue i am facing is that 
![error](https://user-images.githubusercontent.com/31198893/46969404-9027bb80-d0d3-11e8-9ad0-d7b87e243ce3.png)
sorry for so many issues :)

**Comment by alexdor** [comment]
@tabshaikh this means that it tried to proxy the backend request to localhost:4010 but it failed. You can resolve this by removing lines 45 till 50 from here https://github.com/ossn/fixme/blob/master/src/conf/endpoints.ts#L45
