### ISSUE TITLE
Navigating to the Issues page in Chrome is scrolled down a little

### ISSUE THREAD

**Issue by tapasya234** [ossn/fixme#40]
When you navigate to the issues page after typing a language in "I do my magic in" search bar, the scroll bar is not at the top of the page. The bug is present only in Chrome browser and I tested in Chrome, Firefox, and Edge.

**Comment by himankpathak** [comment]
yeaa verified this bug in my browser too. Only happens in chrome. Its sure looks bad when it starts from mid, also when you change the filter on the issues page, page does not scroll to top.
