### ISSUE TITLE
Update Description and Readme with more info

### ISSUE THREAD

**Issue by haxzie** [ossn/fixme#47]
Hello :wave: 
Just found out that this repo is missing some of the important things which might help new contributors understand the project better. ( I had a hard time figuring out what this repo was about)

- The description and website link of this repo is left empty 
- No texts explaining what this project is or what it does

If the maintainers could help with this, that'd be of great help for new contributors :smile:

**Comment by alexdor** [comment]
Hello @haxzie, have a look at the comments of #29 , it would be nice if you could make a pull request adding some of those info to the readme : )

**Comment by haxzie** [comment]
Sure, I'll be working on it :+1:
