### ISSUE TITLE
Issues counter in project tile not uniform

### ISSUE THREAD

**Issue by harsh-2711** [ossn/fixme#83]
The issues counter in the project tiles isn't uniform i.e. some have issues written behind the counter and some have issues written below them.

<img width="1322" alt="screenshot 2018-10-20 at 22 46 52" src="https://user-images.githubusercontent.com/32356267/47258562-92ff2380-d4ba-11e8-8c3c-2a90568f3d21.png">

Also the issues and the setup counters clutters the space. There should be some space between them to make them easily distinguishable.

**Do you want to work on this issue?**
Yes

**Comment by 97amarnathk** [comment]
Can I take this issue?

**Comment by alexdor** [comment]
you can go for it @97amarnathk

**Comment by harsh-2711** [comment]
I am working on this issue

**Comment by 97amarnathk** [comment]
@alexdor  There are 0 projects listed. So I cannot see the bug. How to fill dummy data?
