### ISSUE TITLE
Add .vscode directory to .gitignore

### ISSUE THREAD

**Issue by haxzie** [ossn/fixme#88]
Hello There :wave: 
Any thoughts about git-ignoring the .vscode directory? Since the `settings.json` or the directory doesn't contain any specific configuration, debug or task-specific settings, isn't it good to ignore the directory from version control or having it on GitHub?

**Comment by alexdor** [comment]
Hello, I didn’t add it on gitignore because I was planning to add the debug options, but that never happens 😅 So yeah we should remove the file and add it to gitignore. Do you want to create a pr?

**Comment by haxzie** [comment]
Sure, 'd be happy to do it :+1:

**Comment by alexdor** [comment]
Thank you @haxzie : )
