### ISSUE TITLE
Broken Images In Project

### ISSUE THREAD

**Issue by siddhant1** [ossn/fixme#94]
In Project Section some projects (Common Voice,Blockly) have broken image link and the alt is showing up, we should either update the links or show a placeholder image.

![image](https://user-images.githubusercontent.com/30566406/53011314-1d09c980-3466-11e9-95bd-f41cfcd0008f.png)

**Comment by bmiddha** [comment]
The logo image for the common voice project `https://voice.mozilla.org/img/robot-greetings.png` results in a 404 error.
Needs to be replaced on the back-end with another logo, such as `https://voice.mozilla.org/img/cv-logo-bw.svg`

**Comment by siddhant1** [comment]
Sending in a pr soon

**Comment by siddhant1** [comment]
sent a PR to fixme_backend

**Comment by ashu8912** [comment]
This issue can now be closed As this was related to a fix that was to be done at the fixme_backend 
url for each project logo,link,Tags associated with the project comes from backend
The frontend doesn't have control over it

So anybody has issue regarding broken links or improper tags to a project
raise an issue at the fixme_backend repository.

**Comment by siddhant1** [comment]
@bacharakis can you change the url from the admin side , the pr in the backend was merged but looks like it had no effect

**Comment by alexdor** [comment]
Sounds like we should also handle image loading errors, I don't know if someone wants to tackle this

**Comment by siddhant1** [comment]
Yes , I think we should add a placeholder image in place of that and yeah I can work on this part later

**Comment by siddhant1** [comment]
Working!

**Comment by alexdor** [comment]
Yeah I've edited it directly on the db. And I've opened #130 to handle loading errors
