### ISSUE TITLE
Change Mobile Hamburger Menu UI,

### ISSUE THREAD

**Issue by siddhant1** [ossn/fixme#98]
![screenshot_2019-02-19 fixme](https://user-images.githubusercontent.com/30566406/53037034-28c5b200-349f-11e9-8311-962d311ef51d.png)

I think the facebook and other icons should be big and spaced out , also all the list items should be spaced out as well

**Comment by Paarmita** [comment]
@siddhant1 Can I work on this?
And I think we could put icons in a row. Let me know your suggestions on it.

**Comment by alexdor** [comment]
There is pr by @bmiddha #102 that has a few changes requested. I don't think that @bmiddha is going to continue it (@bmiddha feel free to correct me if I'm wrong), so yeah I think that you can work on it

**Comment by alexdor** [comment]
it looks like #117 addresses all of the issues here.
