### ISSUE TITLE
Github redirection is not working

### ISSUE THREAD

**Issue by bacharakis** [ossn/fixme#99]
The issues are not clickable so the users can't be redirected to the GitHub issues.

**Comment by alx168** [comment]
I want to work on this

**Comment by kpate262** [comment]
I also want to work on this.

**Comment by atlema2** [comment]
I also want to work on this

**Comment by alx168** [comment]
[HPM] Error occurred while trying to proxy request /api/projects from localhost:4010 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
Proxy error: Could not proxy request /api/projects from localhost:4010 to http://localhost:3000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Error encountered while trying to access the projects available after selecting options.

**Comment by kpate262** [comment]
iOS: works on Chrome version = 70.0.3538.75,  but doesn't work on safari iOS: 12.1.4

**Comment by atlema2** [comment]
Does not work on firefox version 64.0

**Comment by kpate262** [comment]
Windows: works on Chrome Version 72.0.3626.119, but does not work on version 65.0.1 on FireFox

**Comment by alx168** [comment]
broken on firefox for android for 65.0.1

**Comment by bacharakis** [comment]
Hey @bmiddha check this out: https://developers.google.com/web/tools/lighthouse/audits/noopener

**Comment by siddhant1** [comment]
Ref #101 added this vulnerability , should I fix it?

**Comment by alexdor** [comment]
For anyone wanting to fix this issue have a look at my commend https://github.com/ossn/fixme/pull/101#pullrequestreview-207132093 it is going to save you a few minutes of googling : )

**Comment by siddhant1** [comment]
ref #110

**Comment by siddhant1** [comment]
I think we can close this now
